version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: normal
artifacts:
- path: KafkaWindowsServiceWrapper\bin\Debug\KafkaWindowsServiceWrapper.exe
- path: KafkaWindowsServiceWrapper\bin\Debug\KafkaWindowsServiceWrapper.exe.config
deploy:
  release: v$(appveyor_build_version)
  description: 'Automatic release'
  provider: GitHub
  auth_token:
    secure: JeugoAg7I3+r9378cO4Tgo5ystDLa7cOf/8fmplBOYZfHGYUBnIriyDhplBRIn32
  artifact: KafkaWindowsServiceWrapper\bin\Debug\KafkaWindowsServiceWrapper.exe
  draft: false
  prerelease: false
  on:
    branch: master
